### ISSUE TITLE
提出コードの出力と想定出力の行数が異なる際のジャッジ不備

### ISSUE THREAD

**Issue by riantkb** [earlgray283/cafecoder-judge#25]
ジャッジに関するバグ報告です（どこに送ればいいのかわからなかったのでここに書かせていただきます）。
本当は修正までやって PR を送れれば良かったんですが、ローカルで立てる方法がわからなかったため、すみません…。

## 起きている現象
「想定解が複数行に渡る場合、一行目さえあっていれば AC を取ることができる」という状態になっています。
提出例：https://cafecoder.top/contests/joi_summer_seminner_2020/submits/439
（複数ケースを処理する存在する問題ですが、最初の1ケースだけ出力しても AC となっています）

また、以下のように無駄な出力があっても AC となります
提出例：https://cafecoder.top/contests/release_test/submits/198

## 原因
https://github.com/cafecoder-dev/cafecoder-judge/blob/aae1b029eabda40b669974cde7f86d4f02f6b97b/src/judgelib/judgelib.go#L311-L318
ここが良くなくて、`min(想定解の行数, 出力の行数)` までしか出力をチェックしていないので、出力されている範囲で答えがあっていれば正答と判定されてしまいます（より正確には、出力の末尾に改行がある場合にはそれも一行とみなされるため、出力の末尾に改行をつけない必要があります）。
また、出力の方が多くても同様にそれを無視するので出力の最後に変な文字が入っていても AC となります（これについては実害はないと思いますが）

## 解決策
`min(想定解の行数, 出力の行数)` ではなく `max(想定解の行数, 出力の行数)` までチェックするのが一番簡単な解決法だとは思います（配列外の場合は代わりに空文字列と比較すれば問題なさそう？）。

ただ、ジャッジコード上にこのような判定コードを置いておくよりもべつで書いてそれに出力と想定解を渡してチェックさせるのが（スペシャルジャッジ等も考えると）汎用的で良い方法だと思います。
https://github.com/yosupo06/library-checker-problems/blob/master/sample/aplusb/checker.cpp
このような出力の比較を行うジャッジコードを用意してそれを呼ぶ、ということをしているジャッジが多いような気はします。

**Comment by earlgray283** [comment]
バグのご報告と解決策の提案を頂きありがとうございます。

### 修正点
1. `max(想定解の行数, 出力の行数)` までチェックするように修正しました。これにより、「想定解が複数行に渡る場合、一行目さえあっていれば AC を取ることができるバグ」と「無駄な出力があっても AC となるバグ」が除去されました。

2. 汎用性を高めるため、判別のコードをライブラリ化しました。

3. 誤 AC の提出をリジャッジさせて頂きました。
https://cafecoder.top/contests/joi_summer_seminner_2020/submits/439
https://cafecoder.top/contests/release_test/submits/198

以上三点の修正を施しました。
https://github.com/cafecoder-dev/cafecoder-judge/pull/26 を確認頂けると幸いです。よろしくお願い致します。

**Comment by riantkb** [comment]
#26 を確認しました。見たところおそらく問題ないと思います。

**Comment by earlgray283** [comment]
確認頂きありがとうございます。
また何かバグ等ございましたらご報告頂けると幸いです。よろしくお願い致します。
